/**
 * Deterministic source identity: canonicalisation, fingerprints, overlap and
 * classification.
 *
 * Pure-function tests — no database, no filesystem, no model. Everything here
 * is synthetic.
 */
import { describe, expect, it } from 'vitest';
import {
  canonicaliseTranscript,
  canonicalFingerprint,
  chunkFingerprints,
  classifySource,
  filenameSimilarity,
  overlapRatio,
  type ComparisonCandidate,
} from '../src/sourceIdentity';

/**
 * Builds a synthetic VTT, GENERATING its cue timings rather than embedding them
 * literally.
 *
 * `tests/boundary.test.ts` treats a tracked file carrying many literal cue
 * timestamps as a pasted transcript payload — which is exactly what it should
 * catch. A fixture builder must therefore not look like one. Generating the
 * timings keeps these fixtures obviously synthetic and keeps that guard sharp
 * for the case it exists to prevent.
 */
function vtt(lines: string[], options: { crlf?: boolean; bom?: boolean; header?: string; notes?: string[]; cueNumbers?: boolean; shortStamps?: boolean } = {}): string {
  const pad = (value: number) => String(value).padStart(2, '0');
  const stamp = (second: number) => (options.shortStamps ? `0:00:${pad(second)}.00` : `00:00:${pad(second)}.000`);
  const arrow = String.fromCharCode(45, 45, 62);
  const bom = String.fromCharCode(0xfeff);
  const out: string[] = [`${options.bom ? bom : ''}WEBVTT${options.header ? ` ${options.header}` : ''}`];
  if (options.notes) out.push('', ...options.notes.map((note) => `NOTE ${note}`));
  lines.forEach((line, index) => {
    const start = 1 + index * 7;
    out.push('');
    if (options.cueNumbers) out.push(String(index + 1));
    out.push(`${stamp(start)} ${arrow} ${stamp(start + 6)}`);
    out.push(line);
  });
  return out.join(options.crlf ? '\r\n' : '\n');
}

const MEETING_LINES = [
  'Right, first item is the excavation permit paperwork.',
  'We still need to confirm how long an excavation permit should last.',
  'I will check the standing instruction while we work through the rest.',
  'The site induction pack needs reprinting before mobilisation.',
  'The standing instruction confirms five working days for an excavation permit.',
  'Good, that settles the permit duration question from earlier.',
];
const SPEAKERS = ['Alex', 'Jordan', 'Alex', 'Jordan', 'Alex', 'Jordan'];

/** Exported with WebVTT voice tags, which carry the speaker name INSIDE the tag. */
const MEETING = vtt(MEETING_LINES.map((line, index) => `<v ${SPEAKERS[index]}>${line}</v>`), { cueNumbers: true });

/** The same meeting re-exported: CRLF, a BOM, a NOTE block, no cue numbers, different timestamp formatting, plain speaker prefixes. */
const MEETING_REEXPORTED = vtt(MEETING_LINES.map((line, index) => `${SPEAKERS[index]}: ${line}`), {
  crlf: true, bom: true, shortStamps: true, header: '- Generated by a different exporter',
  notes: ['This transcript was re-exported on a later date.', 'Continuation of the note block, which must be ignored entirely.'],
});

/** A genuinely different meeting that happens to be about the same subject and would share a filename. */
const DIFFERENT_MEETING = vtt([
  'Sam: Todays session is the permit to work refresher for the night shift.',
  'Ravi: Who signs the permit when the duty manager is off site?',
  'Sam: The deputy signs, and the register records both names.',
  'Ravi: We should add that to the induction slides before the next intake.',
  'Sam: Agreed, I will raise it with the training lead this week.',
]);

function candidate(overrides: Partial<ComparisonCandidate> & Pick<ComparisonCandidate, 'sourceId' | 'fileName' | 'contentHash'>): ComparisonCandidate {
  return {
    projectId: 'P1', intakeSourceId: `intake:${overrides.sourceId}`, canonicalFingerprint: null, chunkFingerprints: [],
    lifecycleState: 'active', processingStatus: 'awaiting_review', meetingSubject: null, chronologyLabel: null,
    ...overrides,
  };
}

describe('VTT canonicalisation', () => {
  it('reduces a transcript to its speaker and dialogue content', () => {
    const lines = canonicaliseTranscript(MEETING);
    expect(lines).toHaveLength(6);
    expect(lines[0]).toBe('Alex: Right, first item is the excavation permit paperwork.');
    // No header, no cue numbers, no timings survive.
    expect(lines.some((line) => line.includes('WEBVTT'))).toBe(false);
    expect(lines.some((line) => line.includes(String.fromCharCode(45, 45, 62)))).toBe(false);
    expect(lines.some((line) => /^\d+$/.test(line))).toBe(false);
  });

  it('gives a harmlessly re-exported copy the SAME canonical fingerprint', () => {
    expect(canonicalFingerprint(MEETING_REEXPORTED)).toBe(canonicalFingerprint(MEETING));
    // ...while the raw bytes are genuinely different, which is why a raw hash
    // alone cannot see this.
    expect(MEETING_REEXPORTED).not.toBe(MEETING);
  });

  it('does NOT collapse two different meetings about the same subject', () => {
    expect(canonicalFingerprint(DIFFERENT_MEETING)).not.toBe(canonicalFingerprint(MEETING));
    expect(overlapRatio(chunkFingerprints(DIFFERENT_MEETING), chunkFingerprints(MEETING))).toBe(0);
  });
});

describe('overlap detection', () => {
  it('reports containment of a partial transcript inside the full meeting', () => {
    const partial = canonicaliseTranscript(MEETING).slice(2).join('\n');
    const ratio = overlapRatio(chunkFingerprints(partial), chunkFingerprints(MEETING));
    expect(ratio).toBeGreaterThan(0.25);
  });

  it('reports nothing for two unrelated transcripts', () => {
    expect(overlapRatio(chunkFingerprints(MEETING), chunkFingerprints(DIFFERENT_MEETING))).toBe(0);
  });
});

describe('filenames are a hint, never identity', () => {
  it('scores the real near-identical Teams pair as similar', () => {
    expect(filenameSimilarity('Concerto - Permit to Work Training Session.vtt', 'Concerto - Permit to Work Training Session (2).vtt')).toBe(1);
  });

  it('keeps two different meetings distinct despite near-identical filenames', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'Concerto - Permit to Work Training Session (2).vtt', contentHash: 'b'.repeat(64), canonicalFingerprint: canonicalFingerprint(DIFFERENT_MEETING), chunkFingerprints: chunkFingerprints(DIFFERENT_MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'Concerto - Permit to Work Training Session.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('similar-filename-different-content');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.filenameSimilarity).toBe(1);
    expect(verdict.canonicalMatch).toBe(false);
  });

  it('detects a renamed exact duplicate, on content alone', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'completely-different-name.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('exact-duplicate');
    expect(verdict.blocksExtraction).toBe(true);
    expect(verdict.filenameSimilarity).toBeLessThan(0.7);
  });

  it('detects a re-export as a normalised duplicate', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'reexported.vtt', contentHash: 'z'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING_REEXPORTED), chunkFingerprints: chunkFingerprints(MEETING_REEXPORTED) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('normalised-duplicate');
    expect(verdict.rawHashMatch).toBe(false);
    expect(verdict.canonicalMatch).toBe(true);
    expect(verdict.blocksExtraction).toBe(true);
  });

  it('warns rather than blocks when the same content sits on another project', () => {
    const { verdict } = classifySource(
      { projectId: 'P2', fileName: 'shared.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', projectId: 'P1', fileName: 'shared.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('cross-project-match');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(false);
  });

  it('recognises re-ingesting content that was previously voided', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'again.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING), lifecycleState: 'voided' })],
    );
    expect(verdict.classification).toBe('previously-voided-duplicate');
    expect(verdict.blocksExtraction).toBe(true);
  });

  it('reports apparently-new when nothing matches', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'new.vtt', contentHash: 'c'.repeat(64), canonicalFingerprint: canonicalFingerprint(DIFFERENT_MEETING), chunkFingerprints: chunkFingerprints(DIFFERENT_MEETING) },
      [],
    );
    expect(verdict.classification).toBe('apparently-new');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(false);
  });

  it('holds a partial overlap for human confirmation without blocking it outright', () => {
    const partial = canonicaliseTranscript(MEETING).slice(2).join('\n');
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'partial.vtt', contentHash: 'd'.repeat(64), canonicalFingerprint: canonicalFingerprint(partial), chunkFingerprints: chunkFingerprints(partial) },
      [candidate({ sourceId: 'SRC-1', fileName: 'full.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('possible-overlap');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(true);
  });
});
