/**
 * Deterministic source identity: canonicalisation, fingerprints, overlap and
 * classification.
 *
 * Pure-function tests — no database, no filesystem, no model. Everything here
 * is synthetic.
 */
import { describe, expect, it } from 'vitest';
import {
  canonicaliseTranscript,
  canonicalFingerprint,
  chunkFingerprints,
  classifySource,
  filenameSimilarity,
  overlapRatio,
  type ComparisonCandidate,
} from '../src/sourceIdentity';

const MEETING = [
  'WEBVTT',
  '',
  '1',
  '00:00:01.000 --> 00:00:06.000',
  '<v Alex>Right, first item is the excavation permit paperwork.</v>',
  '',
  '2',
  '00:00:07.000 --> 00:00:13.000',
  '<v Jordan>We still need to confirm how long an excavation permit should last.</v>',
  '',
  '3',
  '00:00:14.000 --> 00:00:19.000',
  '<v Alex>I will check the standing instruction while we work through the rest.</v>',
  '',
  '4',
  '00:00:20.000 --> 00:00:25.000',
  '<v Jordan>The site induction pack needs reprinting before mobilisation.</v>',
  '',
  '5',
  '00:00:26.000 --> 00:00:33.000',
  '<v Alex>The standing instruction confirms five working days for an excavation permit.</v>',
  '',
  '6',
  '00:00:34.000 --> 00:00:39.000',
  '<v Jordan>Good, that settles the permit duration question from earlier.</v>',
].join('\n');

/** The same meeting re-exported: CRLF, a NOTE block, no cue numbers, different timestamp formatting, typographic quotes, a BOM. */
const MEETING_REEXPORTED = [
  '﻿WEBVTT - Generated by a different exporter',
  '',
  'NOTE This transcript was re-exported on a later date.',
  'NOTE Continuation of the note block, which must be ignored entirely.',
  '',
  '0:00:01.00 --> 0:00:06.00',
  'Alex: Right, first item is the excavation permit paperwork.',
  '',
  '0:00:07.00 --> 0:00:13.00',
  'Jordan: We still need to confirm how long an excavation permit should last.',
  '',
  '0:00:14.00 --> 0:00:19.00',
  'Alex: I will check the standing instruction while we work through the rest.',
  '',
  '0:00:20.00 --> 0:00:25.00',
  'Jordan: The site induction pack needs reprinting before mobilisation.',
  '',
  '0:00:26.00 --> 0:00:33.00',
  'Alex: The standing instruction confirms five working days for an excavation permit.',
  '',
  '0:00:34.00 --> 0:00:39.00',
  'Jordan: Good, that settles the permit duration question from earlier.',
].join('\r\n');

/** A genuinely different meeting that happens to be about the same subject and would share a filename. */
const DIFFERENT_MEETING = [
  'WEBVTT',
  '',
  '00:00:01.000 --> 00:00:06.000',
  'Sam: Todays session is the permit to work refresher for the night shift.',
  '',
  '00:00:07.000 --> 00:00:13.000',
  'Ravi: Who signs the permit when the duty manager is off site?',
  '',
  '00:00:14.000 --> 00:00:19.000',
  'Sam: The deputy signs, and the register records both names.',
  '',
  '00:00:20.000 --> 00:00:26.000',
  'Ravi: We should add that to the induction slides before the next intake.',
  '',
  '00:00:27.000 --> 00:00:33.000',
  'Sam: Agreed, I will raise it with the training lead this week.',
  '',
  '00:00:34.000 --> 00:00:40.000',
  'Ravi: Anything else on night shift cover before we close?',
].join('\n');

function candidate(overrides: Partial<ComparisonCandidate> & Pick<ComparisonCandidate, 'sourceId' | 'fileName' | 'contentHash'>): ComparisonCandidate {
  return {
    projectId: 'P1', intakeSourceId: `intake:${overrides.sourceId}`, canonicalFingerprint: null, chunkFingerprints: [],
    lifecycleState: 'active', processingStatus: 'awaiting_review', meetingSubject: null, chronologyLabel: null,
    ...overrides,
  };
}

describe('VTT canonicalisation', () => {
  it('reduces a transcript to its speaker and dialogue content', () => {
    const lines = canonicaliseTranscript(MEETING);
    expect(lines).toHaveLength(6);
    expect(lines[0]).toBe('Alex: Right, first item is the excavation permit paperwork.');
    // No header, no cue numbers, no timings survive.
    expect(lines.some((line) => line.includes('WEBVTT'))).toBe(false);
    expect(lines.some((line) => line.includes('-->'))).toBe(false);
    expect(lines.some((line) => /^\d+$/.test(line))).toBe(false);
  });

  it('gives a harmlessly re-exported copy the SAME canonical fingerprint', () => {
    expect(canonicalFingerprint(MEETING_REEXPORTED)).toBe(canonicalFingerprint(MEETING));
    // ...while the raw bytes are genuinely different, which is why a raw hash
    // alone cannot see this.
    expect(MEETING_REEXPORTED).not.toBe(MEETING);
  });

  it('does NOT collapse two different meetings about the same subject', () => {
    expect(canonicalFingerprint(DIFFERENT_MEETING)).not.toBe(canonicalFingerprint(MEETING));
    expect(overlapRatio(chunkFingerprints(DIFFERENT_MEETING), chunkFingerprints(MEETING))).toBe(0);
  });
});

describe('overlap detection', () => {
  it('reports containment of a partial transcript inside the full meeting', () => {
    const partial = canonicaliseTranscript(MEETING).slice(2).join('\n');
    const ratio = overlapRatio(chunkFingerprints(partial), chunkFingerprints(MEETING));
    expect(ratio).toBeGreaterThan(0.25);
  });

  it('reports nothing for two unrelated transcripts', () => {
    expect(overlapRatio(chunkFingerprints(MEETING), chunkFingerprints(DIFFERENT_MEETING))).toBe(0);
  });
});

describe('filenames are a hint, never identity', () => {
  it('scores the real near-identical Teams pair as similar', () => {
    expect(filenameSimilarity('Concerto - Permit to Work Training Session.vtt', 'Concerto - Permit to Work Training Session (2).vtt')).toBe(1);
  });

  it('keeps two different meetings distinct despite near-identical filenames', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'Concerto - Permit to Work Training Session (2).vtt', contentHash: 'b'.repeat(64), canonicalFingerprint: canonicalFingerprint(DIFFERENT_MEETING), chunkFingerprints: chunkFingerprints(DIFFERENT_MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'Concerto - Permit to Work Training Session.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('similar-filename-different-content');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.filenameSimilarity).toBe(1);
    expect(verdict.canonicalMatch).toBe(false);
  });

  it('detects a renamed exact duplicate, on content alone', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'completely-different-name.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('exact-duplicate');
    expect(verdict.blocksExtraction).toBe(true);
    expect(verdict.filenameSimilarity).toBeLessThan(0.7);
  });

  it('detects a re-export as a normalised duplicate', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'reexported.vtt', contentHash: 'z'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING_REEXPORTED), chunkFingerprints: chunkFingerprints(MEETING_REEXPORTED) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('normalised-duplicate');
    expect(verdict.rawHashMatch).toBe(false);
    expect(verdict.canonicalMatch).toBe(true);
    expect(verdict.blocksExtraction).toBe(true);
  });

  it('warns rather than blocks when the same content sits on another project', () => {
    const { verdict } = classifySource(
      { projectId: 'P2', fileName: 'shared.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', projectId: 'P1', fileName: 'shared.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('cross-project-match');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(false);
  });

  it('recognises re-ingesting content that was previously voided', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'again.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) },
      [candidate({ sourceId: 'SRC-1', fileName: 'original.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING), lifecycleState: 'voided' })],
    );
    expect(verdict.classification).toBe('previously-voided-duplicate');
    expect(verdict.blocksExtraction).toBe(true);
  });

  it('reports apparently-new when nothing matches', () => {
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'new.vtt', contentHash: 'c'.repeat(64), canonicalFingerprint: canonicalFingerprint(DIFFERENT_MEETING), chunkFingerprints: chunkFingerprints(DIFFERENT_MEETING) },
      [],
    );
    expect(verdict.classification).toBe('apparently-new');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(false);
  });

  it('holds a partial overlap for human confirmation without blocking it outright', () => {
    const partial = canonicaliseTranscript(MEETING).slice(2).join('\n');
    const { verdict } = classifySource(
      { projectId: 'P1', fileName: 'partial.vtt', contentHash: 'd'.repeat(64), canonicalFingerprint: canonicalFingerprint(partial), chunkFingerprints: chunkFingerprints(partial) },
      [candidate({ sourceId: 'SRC-1', fileName: 'full.vtt', contentHash: 'a'.repeat(64), canonicalFingerprint: canonicalFingerprint(MEETING), chunkFingerprints: chunkFingerprints(MEETING) })],
    );
    expect(verdict.classification).toBe('possible-overlap');
    expect(verdict.blocksExtraction).toBe(false);
    expect(verdict.requiresDecision).toBe(true);
  });
});
